# Generated by Django 4.2.6 on 2024-03-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=1000)),
                ('contact', models.EmailField(max_length=1000)),
                ('age', models.IntegerField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('salary', models.CharField(max_length=1000)),
            ],
        ),
    ]
