# Generated by Django 4.2.6 on 2024-03-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_employee_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('year', models.IntegerField(max_length=1000)),
                ('date_purchased', models.DateField(max_length=1000)),
                ('milleage', models.IntegerField()),
                ('color', models.CharField(max_length=1000)),
                ('maintanance', models.CharField(max_length=1000)),
            ],
        ),
    ]
